#############################################################################
# Makefile for building: antico-deluxe
# Generated by qmake (2.01a) (Qt 4.5.0) on: ?? ???? 26 15:21:21 2009
# Project:  antico-deluxe.pro
# Template: subdirs
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++-64 -unix -o Makefile antico-deluxe.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-amelib \
		sub-wm \
		sub-syspref

amelib/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) amelib/ || $(MKDIR) amelib/ 
	cd amelib/ && $(QMAKE) amelib.pro -spec /usr/share/qt/mkspecs/linux-g++-64 -unix -o $(MAKEFILE)
sub-amelib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) amelib/ || $(MKDIR) amelib/ 
	cd amelib/ && $(QMAKE) amelib.pro -spec /usr/share/qt/mkspecs/linux-g++-64 -unix -o $(MAKEFILE)
sub-amelib: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE)
sub-amelib-make_default-ordered: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) 
sub-amelib-make_default: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) 
sub-amelib-make_first-ordered: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) first
sub-amelib-make_first: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) first
sub-amelib-all-ordered: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) all
sub-amelib-all: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) all
sub-amelib-clean-ordered: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) clean
sub-amelib-clean: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) clean
sub-amelib-distclean-ordered: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-amelib-distclean: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-amelib-install_subtargets-ordered: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) install
sub-amelib-install_subtargets: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) install
sub-amelib-uninstall_subtargets-ordered: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-amelib-uninstall_subtargets: amelib/$(MAKEFILE) FORCE
	cd amelib/ && $(MAKE) -f $(MAKEFILE) uninstall
wm/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) wm/ || $(MKDIR) wm/ 
	cd wm/ && $(QMAKE) wm.pro -spec /usr/share/qt/mkspecs/linux-g++-64 -unix -o $(MAKEFILE)
sub-wm-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) wm/ || $(MKDIR) wm/ 
	cd wm/ && $(QMAKE) wm.pro -spec /usr/share/qt/mkspecs/linux-g++-64 -unix -o $(MAKEFILE)
sub-wm: wm/$(MAKEFILE) FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE)
sub-wm-make_default-ordered: wm/$(MAKEFILE) sub-amelib-make_default-ordered  FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) 
sub-wm-make_default: wm/$(MAKEFILE) FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) 
sub-wm-make_first-ordered: wm/$(MAKEFILE) sub-amelib-make_first-ordered  FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) first
sub-wm-make_first: wm/$(MAKEFILE) FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) first
sub-wm-all-ordered: wm/$(MAKEFILE) sub-amelib-all-ordered  FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) all
sub-wm-all: wm/$(MAKEFILE) FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) all
sub-wm-clean-ordered: wm/$(MAKEFILE) sub-amelib-clean-ordered  FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) clean
sub-wm-clean: wm/$(MAKEFILE) FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) clean
sub-wm-distclean-ordered: wm/$(MAKEFILE) sub-amelib-distclean-ordered  FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) distclean
sub-wm-distclean: wm/$(MAKEFILE) FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) distclean
sub-wm-install_subtargets-ordered: wm/$(MAKEFILE) sub-amelib-install_subtargets-ordered  FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) install
sub-wm-install_subtargets: wm/$(MAKEFILE) FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) install
sub-wm-uninstall_subtargets-ordered: wm/$(MAKEFILE) sub-amelib-uninstall_subtargets-ordered  FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-wm-uninstall_subtargets: wm/$(MAKEFILE) FORCE
	cd wm/ && $(MAKE) -f $(MAKEFILE) uninstall
syspref/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) syspref/ || $(MKDIR) syspref/ 
	cd syspref/ && $(QMAKE) syspref.pro -spec /usr/share/qt/mkspecs/linux-g++-64 -unix -o $(MAKEFILE)
sub-syspref-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) syspref/ || $(MKDIR) syspref/ 
	cd syspref/ && $(QMAKE) syspref.pro -spec /usr/share/qt/mkspecs/linux-g++-64 -unix -o $(MAKEFILE)
sub-syspref: syspref/$(MAKEFILE) FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE)
sub-syspref-make_default-ordered: syspref/$(MAKEFILE) sub-wm-make_default-ordered  FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) 
sub-syspref-make_default: syspref/$(MAKEFILE) FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) 
sub-syspref-make_first-ordered: syspref/$(MAKEFILE) sub-wm-make_first-ordered  FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) first
sub-syspref-make_first: syspref/$(MAKEFILE) FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) first
sub-syspref-all-ordered: syspref/$(MAKEFILE) sub-wm-all-ordered  FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) all
sub-syspref-all: syspref/$(MAKEFILE) FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) all
sub-syspref-clean-ordered: syspref/$(MAKEFILE) sub-wm-clean-ordered  FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) clean
sub-syspref-clean: syspref/$(MAKEFILE) FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) clean
sub-syspref-distclean-ordered: syspref/$(MAKEFILE) sub-wm-distclean-ordered  FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) distclean
sub-syspref-distclean: syspref/$(MAKEFILE) FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) distclean
sub-syspref-install_subtargets-ordered: syspref/$(MAKEFILE) sub-wm-install_subtargets-ordered  FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) install
sub-syspref-install_subtargets: syspref/$(MAKEFILE) FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) install
sub-syspref-uninstall_subtargets-ordered: syspref/$(MAKEFILE) sub-wm-uninstall_subtargets-ordered  FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-syspref-uninstall_subtargets: syspref/$(MAKEFILE) FORCE
	cd syspref/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: antico-deluxe.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -unix -o Makefile antico-deluxe.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -unix -o Makefile antico-deluxe.pro

qmake_all: sub-amelib-qmake_all sub-wm-qmake_all sub-syspref-qmake_all FORCE

make_default: sub-amelib-make_default-ordered sub-wm-make_default-ordered sub-syspref-make_default-ordered FORCE
make_first: sub-amelib-make_first-ordered sub-wm-make_first-ordered sub-syspref-make_first-ordered FORCE
all: sub-amelib-all-ordered sub-wm-all-ordered sub-syspref-all-ordered FORCE
clean: sub-amelib-clean-ordered sub-wm-clean-ordered sub-syspref-clean-ordered FORCE
distclean: sub-amelib-distclean-ordered sub-wm-distclean-ordered sub-syspref-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-amelib-install_subtargets-ordered sub-wm-install_subtargets-ordered sub-syspref-install_subtargets-ordered FORCE
uninstall_subtargets: sub-amelib-uninstall_subtargets-ordered sub-wm-uninstall_subtargets-ordered sub-syspref-uninstall_subtargets-ordered FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

